### ISSUE TITLE
New sub-module layout

### ISSUE THREAD

**Issue by claudio-rosati** [ControlSystemStudio/org.csstudio.product#36]
@berryma4 I need some help to understand how the new sub-module layout works.

Remember: I'm working on forked version of all repositories.

![0](https://user-images.githubusercontent.com/10833922/34712767-51eb506a-f524-11e7-91f1-e8f34f9cb88f.png)

Now, after having merged the master branch of the `org.csstudio.product` repository, inside it I see 3 empty folders (`cs-studio`, `cs-studio-thirdparty`, and `maven-osgi-bundles`). Why? And, more important, why are they empty? Should them be the corresponding ones up one level?

![1](https://user-images.githubusercontent.com/10833922/34712925-da3d2b64-f524-11e7-8fd7-ddc5413c2e49.png)

Moreover, the `.gitmodules` file contains:

```
[submodule "maven-osgi-bundles"]
	path = maven-osgi-bundles
	url = https://github.com/ControlSystemStudio/maven-osgi-bundles.git
[submodule "cs-studio-thirdparty"]
	path = cs-studio-thirdparty
	url = https://github.com/ControlSystemStudio/cs-studio-thirdparty.git
[submodule "cs-studio"]
	path = cs-studio
	url = https://github.com/ControlSystemStudio/cs-studio
```

Should I change the URLs to my forked repositories?

Last, the `org.csstudio.ess.product` repository was originally created by Kunal for ESS mimicking the `org.csstudio.product` one, and afterwards updated and maintained by myself. Should I do change it accordingly? If yes, what are the main things to do?

Claudio

**Comment by claudio-rosati** [comment]
Hello @shroffk,

first of all let me say taht I'm a bit disappointed coming back from holidays and find – again – the build system broken: from this point of view I really hope phoebus-based implementation will substitute the whole CS-Studio stuff as soon as possible. Since I started working at ESS I spent more tima having the build system working than doing real development, and this is a bit frustrating.

Then, trying to minimize changes I've just updated the `.gitmodules` to 

```
[submodule "maven-osgi-bundles"]
	path = maven-osgi-bundles
	url = https://github.com/ESSICS/maven-osgi-bundles.git
[submodule "cs-studio-thirdparty"]
	path = cs-studio-thirdparty
	url = https://github.com/ESSICS/cs-studio-thirdparty.git
[submodule "cs-studio"]
	path = cs-studio
	url = https://github.com/ESSICS/cs-studio.git
```

and my local shellscripts and everything builds fine after aving synchronized all forked repositories to the last version of their master branch.

When I push all the changes to my forked repositories and try my Jenkins development pipeline it breaks not where expected (i.e. the changed product file structure), but

```
...
00:16:46.578 [INFO] Computing target platform for MavenProject: org.csstudio:org.csstudio.vtype.pv:4.5.0-SNAPSHOT @ /home/jenkins/workspace/ESS-CS-Studio-Development/cs-studio/core/base/base-plugins/org.csstudio.vtype.pv/pom.xml
00:16:46.840 [INFO] Resolving dependencies of MavenProject: org.csstudio:org.csstudio.vtype.pv:4.5.0-SNAPSHOT @ /home/jenkins/workspace/ESS-CS-Studio-Development/cs-studio/core/base/base-plugins/org.csstudio.vtype.pv/pom.xml
00:16:46.841 [INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
00:16:46.841 [ERROR] Cannot resolve project dependencies:
00:16:46.841 [ERROR]   Software being installed: org.csstudio.vtype.pv 4.5.0.qualifier
00:16:46.841 [ERROR]   Missing requirement: org.csstudio.vtype.pv 4.5.0.qualifier requires 'bundle org.epics.pvDataJava 5.0.3' but it could not be found
00:16:46.841 [ERROR] 
00:16:46.841 [ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
00:16:46.841 [ERROR] Cannot resolve dependencies of MavenProject: org.csstudio:org.csstudio.vtype.pv:4.5.0-SNAPSHOT @ /home/jenkins/workspace/ESS-CS-Studio-Development/cs-studio/core/base/base-plugins/org.csstudio.vtype.pv/pom.xml: See log for details -> [Help 1]
...

and I really don't undestand why this is not working.

I am a bit scared about doing a recursive cloning, being that eveything seems working as is locally.
```

**Comment by berryma4** [comment]
https://github.com/ControlSystemStudio/cs-studio/pull/2370
will fix this issue.

**Comment by claudio-rosati** [comment]
@berryma4 
OK, I'll wait for it being merged in the master branch.
What I still not understand is why if a launch a complete clean-and-build locally (with my shellscript) it works. Can be related to the fact tha the script will not clean the `.m2` folder?

**Comment by berryma4** [comment]
Although, we still need diirt to do a release, so cs-studio master pull the correct diirt with jca 2.4.1.
(but, you are building against diirt master, so you should already have jca 2.4.1)

A comment on your build, you will run into build breaks as long as you are building against diirt master.  It is nice that you test against master, but you shouldn't expect it to not break.  You will need to build against diirt releases to expect that.

**Comment by berryma4** [comment]
Yes, you must have a org.epics.pvDataJava 5.0.3 in your build somewhere.  The S3 build still works because there is a pvData pvAccess in the maven-osgi-bundles S3 p2 repo.  But, if you are building locally without the S3 repos, it should be failing because of the name change of the pvdata/pvaccess jars.

Also, because diirt has not been released yet, if you are not building against diirt master, you will have both the new and old jca/pvdata/pvaccess jars.

**Comment by claudio-rosati** [comment]
@berryma4 @shroffk 
About the build...
I supposed one should clone/fork the repositories and build them against the master branch.
DIIRT has no a "release" branch. Is what you are referring the `dirt-all-3.1.6` tag? And if it is the case, why no publish DIIRT on Maven and use it through the `maven-osgi-bundles` project, or the `cs-studio-thirdparty` one, relieving CS-Studio builds from the "release" dependency?

**Comment by shroffk** [comment]
diirt only makes release tags.
The goal is to have it released to maven central (previous releases are on maven). The 3.1.6 release was the first release after the transfer of ownership and we did not have time to sort out all the credentials and permissions, with this release that should be sorted.

**Comment by claudio-rosati** [comment]
@berryma4 @shroffk 
OK, so the idea is to have DIIRT on Maven and no more use the DIIRT git repository to build CS-Studio but DIIRT inside `maven-osg-bundles`. Isn't it?

Moreover I still have problems building `cs-studio`: after deleting `~\.m2\repository` I've run my full script locally without any problem.But whe I run the similar pipeline on jankins I have the following:

```
00:31:18.238 [ERROR] Cannot resolve project dependencies:
00:31:18.238 [ERROR]   Software being installed: org.csstudio.archive.reader.ea4 1.0.0.qualifier
00:31:18.238 [ERROR]   Missing requirement: org.csstudio.archive.reader.ea4 1.0.0.qualifier requires 'bundle org.epics.pvAccessJava 4.1.3' but it could not be found
00:31:18.239 [ERROR] 
00:31:18.239 [ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
00:31:18.239 [ERROR] Cannot resolve dependencies of MavenProject: org.csstudio:org.csstudio.archive.reader.ea4:1.0.0-SNAPSHOT @ /home/jenkins/workspace/ESS-CS-Studio-Development/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.reader.ea4/pom.xml: See log for details -> [Help 1]
00:31:18.239 org.apache.maven.MavenExecutionException: Cannot resolve dependencies of MavenProject: org.csstudio:org.csstudio.archive.reader.ea4:1.0.0-SNAPSHOT @ /home/jenkins/workspace/ESS-CS-Studio-Development/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.reader.ea4/pom.xml
00:31:18.239 	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:100)
00:31:18.239 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:274)
00:31:18.239 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
00:31:18.239 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
00:31:18.239 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
00:31:18.239 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
00:31:18.239 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
00:31:18.239 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
00:31:18.239 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
00:31:18.239 	at java.lang.reflect.Method.invoke(Method.java:498)
00:31:18.239 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
00:31:18.239 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
00:31:18.239 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
00:31:18.239 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
00:31:18.239 Caused by: org.eclipse.tycho.artifacts.DependencyResolutionException: Cannot resolve dependencies of MavenProject: org.csstudio:org.csstudio.archive.reader.ea4:1.0.0-SNAPSHOT @ /home/jenkins/workspace/ESS-CS-Studio-Development/cs-studio/applications/archive/archive-plugins/org.csstudio.archive.reader.ea4/pom.xml
00:31:18.239 	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:202)
00:31:18.239 	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:116)
00:31:18.239 	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies(P2DependencyResolver.java:367)
00:31:18.239 	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies(P2DependencyResolver.java:335)
00:31:18.239 	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:117)
00:31:18.239 	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:95)
00:31:18.239 	... 13 more
00:31:18.239 Caused by: org.eclipse.tycho.p2.util.resolution.ResolverException: See log for details
00:31:18.239 	at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
00:31:18.239 	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:42)
00:31:18.239 	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:195)
00:31:18.239 	... 18 more
```

something I didn't have before.

Any idea?

**Comment by berryma4** [comment]
Thank you, I also noticed this is morning.
https://github.com/ControlSystemStudio/cs-studio/pull/2373
This should be the last of the name changes for pvaccess and pvdata.

**Comment by claudio-rosati** [comment]
@berryma4 
Thank you, it worked now.
I still have a problem in building the `org.csstudio.display.builder`. @kasemir have you an idea of why I cannot build it?

```
01:01:49.961 [INFO] Reactor Summary:
01:01:49.961 [INFO] 
01:01:49.961 [INFO] display-builder ................................... SUCCESS [2.540s]
01:01:49.961 [INFO] org.csstudio.display.builder.util ................. SUCCESS [2.866s]
01:01:49.961 [INFO] org.csstudio.javafx ............................... SUCCESS [1.344s]
01:01:49.961 [INFO] org.csstudio.display.builder.model ................ SUCCESS [3.697s]
01:01:49.961 [INFO] org.csstudio.display.builder.representation ....... SUCCESS [0.470s]
01:01:49.961 [INFO] org.csstudio.javafx.rtplot ........................ SUCCESS [1.364s]
01:01:49.961 [INFO] org.csstudio.display.builder.representation.javafx  SUCCESS [2.685s]
01:01:49.961 [INFO] org.csstudio.display.builder.editor ............... SUCCESS [1.195s]
01:01:49.961 [INFO] org.csstudio.javafx.swt ........................... SUCCESS [0.268s]
01:01:49.961 [INFO] org.csstudio.display.builder.runtime .............. SUCCESS [0.644s]
01:01:49.962 [INFO] org.csstudio.display.builder.rcp .................. SUCCESS [0.702s]
01:01:49.962 [INFO] org.csstudio.display.builder.editor.rcp ........... SUCCESS [0.634s]
01:01:49.962 [INFO] org.csstudio.display.builder.examples ............. SUCCESS [0.227s]
01:01:49.962 [INFO] org.csstudio.display.builder.model.rcp ............ SUCCESS [0.163s]
01:01:49.962 [INFO] org.csstudio.display.builder.model.test ........... SUCCESS [58.003s]
01:01:49.962 [INFO] org.csstudio.display.builder.rcp.test ............. SUCCESS [7.540s]
01:01:49.962 [INFO] org.csstudio.display.builder.representation.swt ... SUCCESS [0.319s]
01:01:49.962 [INFO] org.csstudio.display.builder.representation.test .. SUCCESS [9.747s]
01:01:49.962 [INFO] org.csstudio.display.builder.runtime.test ......... SUCCESS [27.399s]
01:01:49.962 [INFO] org.csstudio.javafx.rtplot.test ................... SUCCESS [13.241s]
01:01:49.962 [INFO] org.csstudio.display.builder.feature .............. SUCCESS [0.801s]
01:01:49.962 [INFO] databrowser ....................................... SUCCESS [0.002s]
01:01:49.962 [INFO] databrowser-plugins ............................... SUCCESS [0.002s]
01:01:49.962 [INFO] org.csstudio.trends.databrowser3 .................. SUCCESS [1.741s]
01:01:49.962 [INFO] org.csstudio.trends.databrowser3.opiwidget ........ SUCCESS [0.410s]
01:01:49.962 [INFO] org.csstudio.trends.databrowser3.bobwidget ........ SUCCESS [0.335s]
01:01:49.962 [INFO] databrowser-features .............................. SUCCESS [0.002s]
01:01:49.962 [INFO] org.csstudio.trends.databrowser3.feature .......... SUCCESS [0.277s]
01:01:49.962 [INFO] org.csstudio.trends.databrowser3.opiwidget.feature  SUCCESS [0.123s]
01:01:49.962 [INFO] org.csstudio.trends.databrowser3.bobwidget.feature  SUCCESS [0.147s]
01:01:49.962 [INFO] repository ........................................ FAILURE [0.098s]
01:01:49.962 [INFO] ------------------------------------------------------------------------
01:01:49.962 [INFO] BUILD FAILURE
01:01:49.962 [INFO] ------------------------------------------------------------------------
01:01:49.962 [INFO] Total time: 4:26.944s
01:01:49.962 [INFO] Finished at: Fri Jan 12 07:16:50 CET 2018
01:01:51.879 [INFO] Final Memory: 330M/1430M
01:01:51.879 [INFO] ------------------------------------------------------------------------
01:01:51.879 [WARNING] The requested profile "platform-default" could not be activated because it does not exist.
01:01:51.879 [WARNING] The requested profile "csstudio-composite-repo-enable" could not be activated because it does not exist.
01:01:51.879 [WARNING] The requested profile "eclipse-sites" could not be activated because it does not exist.
01:01:51.879 [ERROR] Failed to execute goal org.eclipse.tycho:tycho-packaging-plugin:1.0.0:build-qualifier-aggregator (default-build-qualifier-aggregator) on project repository: Execution default-build-qualifier-aggregator of goal org.eclipse.tycho:tycho-packaging-plugin:1.0.0:build-qualifier-aggregator failed: Could not resolve plugin org.epics.caj_null; Path to dependency: -> [Help 1]
```

**Comment by claudio-rosati** [comment]
Thanks to @kasemir that gave me a hint, I've fixed my build.
